# Generated by Django 3.2.6 on 2024-01-27 13:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Card', 'Карта'), ('Payment account', 'Платежный счет')], max_length=100, verbose_name='Тип платежа')),
                ('account_type', models.CharField(choices=[('Debit card', 'Дебетовая карта'), ('Credit card', 'Кредитная карта'), ('Organization account', 'Счёт огранизации'), ('Individual account', 'Счёт физического лица')], max_length=100, verbose_name='Тип карты/счёта')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('card_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Лимит доступных средств')),
            ],
            options={
                'verbose_name': 'Реквизиты',
                'verbose_name_plural': 'Реквизиты',
            },
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма оплаты')),
                ('status', models.CharField(choices=[('Awaiting', 'Ожидает оплаты'), ('Paid', 'Оплачена'), ('Cancelled', 'Отменена')], max_length=100, verbose_name='Статус заявки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('requisites', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='request.requisite', verbose_name='Реквизиты заявки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ('-created',),
            },
        ),
    ]
