# Generated by Django 3.2.6 on 2024-01-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('Ожидает оплаты', 'Ожидает оплаты'), ('Оплачена', 'Оплачена'), ('Отменена', 'Отменена')], max_length=100, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='account_type',
            field=models.CharField(choices=[('Дебетовая карта', 'Дебетовая карта'), ('Кредитная карта', 'Кредитная карта'), ('Счёт огранизации', 'Счёт огранизации'), ('Счёт физического лица', 'Счёт физического лица')], max_length=100, verbose_name='Тип карты/счёта'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='payment_type',
            field=models.CharField(choices=[('Карта', 'Карта'), ('Платежный счет', 'Платежный счет')], max_length=100, verbose_name='Тип платежа'),
        ),
    ]
