# Generated by Django 3.2.6 on 2024-01-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20240129_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='status',
            field=models.CharField(choices=[('Awaiting', 'Ожидает оплаты'), ('Paid', 'Оплачена'), ('Cancelled', 'Отменена')], default=('Awaiting', 'Ожидает оплаты'), max_length=100, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='account_type',
            field=models.CharField(choices=[('Debit card', 'Дебетовая карта'), ('Credit card', 'Кредитная карта'), ('Organization account', 'Счёт огранизации'), ('Individual account', 'Счёт физического лица')], max_length=100, verbose_name='Тип карты/счёта'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='payment_type',
            field=models.CharField(choices=[('Card', 'Карта'), ('Payment account', 'Платежный счет')], max_length=100, verbose_name='Тип платежа'),
        ),
    ]
